repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^(kicad)
  - id: end-of-file-fixer
    exclude: ^(kicad)
  - id: check-toml
  - id: check-json
  - id: check-yaml
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs
  - id: check-added-large-files
    exclude: ^(imgs)
