format = """
$username\
$hostname\
$localip\
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$lua\
$python\
$rust\
$memory_usage\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[line_break]
disabled = true

[character]
success_symbol = "[❯](green)"
error_symbol = "[!](red)"
vimcmd_symbol = "[❯](red)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = 'a'
behind = 'b'
conflicted = '!'
deleted = 'D'
diverged = 'd'
modified = 'm'
renamed = 'r'
staged = 's'
stashed = 'S'
untracked = 'U'
up_to_date = 'u'

[directory]
read_only = " ro"

[git_branch]
symbol = "git "

[python]
symbol = "py "

[package]
symbol = "pkg "

[rust]
symbol = "rs "
