theme = "@catppuccin_macchiato"

[editor]
rulers = [89, 101]
mouse = true
scrolloff = 8
cursorline = true
color-modes = true
bufferline = "always"
idle-timeout = 100
completion-replace = false
completion-trigger-len = 1

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace]
render = { space = "all" }
characters = { space = "·" }

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [
  "mode",
  "file-name",
  "spacer",
  "version-control",
  "spacer",
  "spacer",
  "workspace-diagnostics",
]
right = [
  "file-encoding",
  "spacer",
  "position-percentage",
  "spacer",
  "position",
  "spacer",
  "spinner",
]

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.soft-wrap]
enable = false
wrap-indicator = ""
wrap-at-text-width = true

# Normal Mode Keymaps ----------------------------------------------------------

[keys.normal]

backspace.r = ":config-reload"
# Use explicit paths so LSP and git-gutter work.
backspace.c = ":open ~/.dotfiles/helix/config.toml"
backspace.l = ":open ~/.dotfiles/helix/languages.toml"
backspace.t = ":open todo.md"

minus.z = ":toggle soft-wrap.enable"
minus.i = ":toggle lsp.display-inlay-hints"
minus.t = ":set-language text"

# Navigate splits with Alt-hjkl.
C-k = "jump_view_up"
C-j = "jump_view_down"
C-h = "jump_view_left"
C-l = "jump_view_right"

# Scroll page up and down.
C-A-k = ["scroll_up", "scroll_up", "scroll_up", "scroll_up"]
C-A-j = ["scroll_down", "scroll_down", "scroll_down", "scroll_down"]

# Clear all extra cursors.
C-esc = "keep_primary_selection"

# Delete from cursor to end of the line and enter NORMAL mode.
D = ["extend_to_line_end", "yank", "delete_selection"]

# Change from cursor to end of the line and enter INSERT mode.
C = ["extend_to_line_end", "yank", "change_selection"]

# Yank from cursor to end of the line.
Y = ["extend_to_line_end", "yank", "flip_selections", "collapse_selection"]

# Select from cursor to end of the line.
V = ["extend_to_line_end"]

# Wrap word under cursor.
A-w = [
  "collapse_selection",
  "move_prev_word_start",
  "move_next_word_end",
  "surround_add",
]


# Search word under cursor.
# Use 'n' and 'N' to select other instances.
A-d = [
  "collapse_selection",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
]

# Select and search word under cursor.
# Use 'n' and 'N' to select other instances.
A-s = [
  "collapse_selection",
  "move_prev_word_start",
  "move_next_word_end",
  "search_selection",
  "select_mode",
]


# Yank word under cursor.
A-y = [
  "move_next_word_end",
  "move_prev_word_start",
  "yank",
  "collapse_selection",
]

# Reflow current selection.
A-r = [":reflow", "goto_line_start"]

# Normal Mode Remaps ---

# Remap from C
A-j = "copy_selection_on_next_line"

# Remap from A-C
A-k = "copy_selection_on_prev_line"

# Select Mode Keymaps ----------------------------------------------------------

[keys.select]

# Delete from cursor to end of the line and enter NORMAL mode.
D = ["extend_to_line_end", "yank", "delete_selection"]

# Change from cursor to end of the line and enter INSERT mode.
C = ["extend_to_line_end", "yank", "change_selection"]

# Yank from cursor to end of the line.
Y = ["extend_to_line_end", "yank", "flip_selections", "collapse_selection"]

# Select from cursor to end of the line.
V = ["extend_to_line_end"]

# Select Mode Remaps ---

# Remap from C
A-j = "copy_selection_on_next_line"

# Remap from A-C
A-k = "copy_selection_on_prev_line"
