theme = "@catppuccin_macchiato"

[editor]
rulers = [81, 101]
mouse = true
scrolloff = 8
cursorline = true
color-modes = true
bufferline = "always"
idle-timeout = 100
line-number = "absolute"
completion-replace = false
completion-trigger-len = 1

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.whitespace]
render = { space = "all" }
characters = { space = "·" }

[editor.indent-guides]
render = true
skip-levels = 1

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = [
  "mode",
  "spacer",
  "spinner",
  "file-name",
  "spacer",
  "version-control",
  "workspace-diagnostics",
  "file-modification-indicator",
  "read-only-indicator",
]
right = [
  "file-encoding",
  "spacer",
  "spacer",
  "selections",
  "spacer",
  "position-percentage",
  "spacer",
  "position",
  "total-line-numbers",
]

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "disable"
max-diagnostics = 20
prefix-len = 3

[editor.soft-wrap]
enable = false
wrap-indicator = ""
wrap-at-text-width = true
max-wrap = 100


# Normal Mode Custom Space Keymaps ---------------------------------------------

# Space-Q -- Custom
[keys.normal.space.q]

# Write file.
w = ":write"

# Write file.
S-w = ":write-all"

# Close file.
c = ":buffer-close"

# Quit.
S-q = ":quit"

# Format document.
f = ":format"

# Copy document contents.
e = "@<C-s> @% @<space>y @<C-o> @:echo yanked document to clipboard<ret>"

# Search for any TODO-like strings.
t = "@<space>/ (TODO|FIX|FIXME|WIP|HACK)(\\(.+\\))?:"

# Search for any NOTE-like strings.
n = "@<space>/ (NOTE|QUESTION|MARK)(\\(.+\\))?:"

# Rename the current file.
m = "@:sh mv <C-r>% <C-r>%<C-w>"

# Copy the diagnostic message under the cursor
d = ":yank-diagnostic"

# Reflow current selection.
r = ":reflow"

# Reflow current selection.
l = ":log-open"

# Sort all lines
s = "@<A-s> @:sort <ret> @,"

# Show blame on the current line.
b = ":sh git blame -L %{cursor_line},%{cursor_line} %{buffer_name}"

# Space-T -- Toggle
[keys.normal.space.t]
h = ":toggle file-picker.hidden"
i = ":toggle lsp.display-inlay-hints"
w = ":toggle soft-wrap.enable"
f = ":toggle auto-format"
n = ":toggle insert-final-newline"

# Space-C -- Config
[keys.normal.space.c]
c = ":open ~/.dotfiles/helix/config.toml"
l = ":open ~/.dotfiles/helix/languages.toml"
r = [":config-reload", ":lsp-restart"]


# Normal Mode Keymaps ----------------------------------------------------------

[keys.normal]

# Navigate splits with Control-hjkl.
C-k = "jump_view_up"
C-j = "jump_view_down"
C-h = "jump_view_left"
C-l = "jump_view_right"

# Go to next change.
C-n = "@]g"
# Go to prev change.
C-p = "@[g"

# Go to next diagnostic.
A-n = "@]d"
# Go to prev diagnostic.
A-p = "@[d"

# Scroll page up and down.
C-A-k = ["scroll_up", "scroll_up", "scroll_up", "scroll_up"]
C-A-j = ["scroll_down", "scroll_down", "scroll_down", "scroll_down"]

# Clear all extra cursors.
C-esc = "keep_primary_selection"

# Delete from cursor to end of the line and enter NORMAL mode.
D = ["extend_to_line_end", "yank", "delete_selection"]

# Change from cursor to end of the line and enter INSERT mode.
C = ["extend_to_line_end", "yank", "change_selection"]

# Yank from cursor to end of the line.
Y = ["extend_to_line_end", "yank", "flip_selections", "collapse_selection"]

# Select from cursor to end of the line.
S-l = ["extend_to_line_end"]

# Select from cursor to start of the line.
S-h = ["extend_to_line_start"]

# Select the current line and trim whitespace.
S-x = ["extend_line_below", "trim_selections"]

# TODO: Remap this.
# Search word under cursor.
# Use 'n' and 'N' to select other instances.
# A-d = [
#   "collapse_selection",
#   "move_prev_word_start",
#   "move_next_word_end",
#   "search_selection",
# ]

# TODO: Remap this.
# Search and select word under cursor.
# Use 'n' and 'N' to select other instances.
# A-s = [
#   "collapse_selection",
#   "move_prev_word_start",
#   "move_next_word_end",
#   "search_selection",
#   "select_mode",
# ]

# Yank word under cursor.
A-y = [
  "move_next_word_end",
  "move_prev_word_start",
  "yank",
  "collapse_selection",
]

# Wrap word under cursor.
A-w = [
  "collapse_selection",
  "move_prev_word_start",
  "move_next_word_end",
  "surround_add",
]

# Normal Mode Remaps ---

# Remap from: C
A-j = "copy_selection_on_next_line"

# Remap from: A-C
A-k = "copy_selection_on_prev_line"

# Select Mode Keymaps ----------------------------------------------------------

[keys.select]

# Delete from cursor to end of the line and enter NORMAL mode.
D = ["extend_to_line_end", "yank", "delete_selection"]

# Change from cursor to end of the line and enter INSERT mode.
C = ["extend_to_line_end", "yank", "change_selection"]

# Yank from cursor to end of the line.
Y = ["extend_to_line_end", "yank", "flip_selections", "collapse_selection"]

# Select from cursor to end of the line.
S-l = ["extend_to_line_end"]

# Select from cursor to start of the line.
S-h = ["extend_to_line_start"]

# Wrap selection.
A-w = ["surround_add"]
