# https://github.com/helix-editor/helix/blob/master/languages.toml
#
# Install LSPs:
#   brew install taplo
#   brew install prettier
#   brew install rust-analyzer
#   brew install lua-language-server
#   brew install yaml-language-server
#   brew install ltex-ls
#   brew install pyright
#   pipx install 'python-lsp-server[all]'
#   npm i -g vscode-langservers-extracted
#   npm i -g bash-language-server
#   https://github.com/artempyanykh/marksman

# Rust -------------------------------------------------------------------------

[[language]]
name = "rust"

[language.config]
checkOnSave.command = "clippy"

# Python -----------------------------------------------------------------------

# https://github.com/helix-editor/helix/issues/2293#issuecomment-1110730331
[[language]]
name = "python"
roots = ["pyproject.toml"]
auto-format = true
max-line-length = 88

[language.language-server]
command = "pyright-langserver"
args = ["--stdio"]

# Pyright config
[language.config.analysis]
autoSearchPaths = true
diagnosticMode = "workspace"
useLibraryCodeForTypes = true

[language.formatter]
command = "black"
args = ["-", "--quiet"]

# Lua --------------------------------------------------------------------------

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language.config]
Lua.runtime.version = "LuaJIT"
Lua.diagnostics.globals = [
  # Neovim
  "vim",
  # Hammerspoon
  "hs",
  "spoon",
]

# Bash -------------------------------------------------------------------------

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }

# Markdown ---------------------------------------------------------------------

[[language]]
name = "markdown"
auto-format = true
roots = [".marksman.toml"]

[language.language-server]
command = "ltex-ls" # Good for spell check
# command = "marksman" # Good Markdown LSP
# args = ["server"]

[language.formatter]
command = "prettier"
args = ["--parser", "markdown"]

# CSS --------------------------------------------------------------------------

[[language]]
name = "css"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "css"]

# JSON -------------------------------------------------------------------------

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = "  " }

# TOML -------------------------------------------------------------------------

[[language]]
name = "toml"
auto-format = true

# YAML -------------------------------------------------------------------------

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = "  " }
