# https://github.com/helix-editor/helix/blob/master/languages.toml
#
# Install Language Servers:
#   brew install taplo
#   brew install prettier
#   brew install rust-analyzer
#   brew install lua-language-server
#   brew install yaml-language-server
#   brew install marksman
#   brew install ltex-ls
#   brew install pyright
#   brew install ruff-lsp
#   npm i -g vscode-langservers-extracted
#   npm i -g bash-language-server

# Rust -------------------------------------------------------------------------

[[language]]
name = "rust"
text-width = 100

[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"

# Python -----------------------------------------------------------------------

[[language]]
name = "python"
auto-format = true
text-width = 88
language-servers = ["pyright", "ruff"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "standard"

[language-server.ruff]
command = "ruff-lsp"

[language-server.ruff.config.settings]
lint.args = [
  "--extend-select=E",    # pycodestyle: error
  "--extend-select=W",    # pycodestyle: warning
  "--extend-select=F",    # Pyflakes
  "--extend-select=UP",   # pyupgrade
  "--extend-select=B",    # flake8-bugbear
  "--extend-select=A",    # flake8-builtins
  "--extend-select=C4",   # flake8-comprehensions
  "--extend-select=EM",   # flake8-errmsg
  "--extend-select=EXE",  # flake8-executable
  "--extend-select=ISC",  # flake8-implicit-str-concat
  "--extend-select=Q",    # flake8-quotes
  "--extend-select=RET",  # flake8-return
  "--extend-select=SLF",  # flake8-self
  "--extend-select=SIM",  # flake8-simplify
  "--extend-select=ARG",  # flake8-unused-arguments
  "--extend-select=PTH",  # flake8-use-pathlib
  "--extend-select=PL",   # Pylint
  "--extend-ignore=E501", # line-too-long
]

[language.formatter]
command = "black"
args = ["--quiet", "-"]

# Lua --------------------------------------------------------------------------

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language-server.lua-language-server.config.Lua]
runtime.version = "LuaJIT"
diagnostics.globals = [
  # Hammerspoon
  "hs",
  "spoon",
]

# Bash -------------------------------------------------------------------------

# https://github.com/helix-editor/helix/issues/6896
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }

# Markdown ---------------------------------------------------------------------

[[language]]
name = "markdown"
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = ["marksman", "ltex-ls"]

# Markdown LS
[language-server.marksman]
command = "marksman"

# Good for spell check
[language-server.ltex-ls]
command = "ltex-ls"

[language.formatter]
command = "prettier"
args = ["--parser", "markdown"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'_' = '_'
'<' = '>'

# CSS --------------------------------------------------------------------------

[[language]]
name = "css"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "css"]

# JSON -------------------------------------------------------------------------

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = "    " }

# TOML -------------------------------------------------------------------------

[[language]]
name = "toml"
auto-format = true

# YAML -------------------------------------------------------------------------

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

# Ruby -------------------------------------------------------------------------

[[language]]
name = "ruby"
file-types = [
  "rb",
  "rake",
  "rakefile",
  "irb",
  "gemfile",
  "gemspec",
  "Rakefile",
  "Gemfile",
  "rabl",
  "jbuilder",
  "jb",
  "Podfile",
  "podspec",
  # Additions
  "Brewfile",
  "Brewfile-dump",
]

# Text -------------------------------------------------------------------------

[[language]]
name = "text"
scope = "source.txt"
injection-regex = "txt"
file-types = ["txt"]
roots = []
indent = { tab-width = 2, unit = "  " }

# INI --------------------------------------------------------------------------

[[language]]
name = "ini"
file-types = [
  "ini",
  # Systemd unit files
  "service",
  "automount",
  "device",
  "mount",
  "path",
  "service",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  ".editorconfig",
  "properties",
  "cfg",
  "directory",
  # Additions
  "conf",
]
