# https://github.com/helix-editor/helix/blob/master/languages.toml
#
# Install LSPs:
#   brew install taplo
#   brew install prettier
#   brew install rust-analyzer
#   brew install lua-language-server
#   brew install yaml-language-server
#   cargo install taplo-cli --locked --features lsp
#   pipx install 'python-lsp-server[all]'
#   npm i -g vscode-langservers-extracted
#   npm i -g bash-language-server
#   https://github.com/artempyanykh/marksman

# Rust -------------------------------------------------------------------------

[[language]]
name = "rust"

[language.config]
checkOnSave.command = "clippy"

# Lua --------------------------------------------------------------------------

[[language]]
name = "lua"

[language.config]
Lua.runtime.version = "LuaJIT"
Lua.diagnostics.globals = [
  # Neovim
  "vim",
  # Hammerspoon
  "hs",
  "spoon",
]

# Markdown ---------------------------------------------------------------------

[[language]]
name = "markdown"
auto-format = true
# TEMP: Remove when `master` is released.
# Copied from https://github.com/helix-editor/helix/blob/master/languages.toml
roots = [".marksman.toml"]
language-server = { command = "marksman", args = ["server"] }

[language.formatter]
command = "prettier"
args = ["--config", ".prettierrc", "--parser", "markdown"]

# CSS --------------------------------------------------------------------------

[[language]]
name = "css"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--config", ".prettierrc", "--parser", "css"]

# JSON -------------------------------------------------------------------------

# BUG: Oddly this makes all json indent with tabs rather than spaces.
[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = " " }

# TOML -------------------------------------------------------------------------

[[language]]
name = "toml"
auto-format = true

# YAML -------------------------------------------------------------------------

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = " " }
