# https://github.com/helix-editor/helix/blob/master/languages.toml
#
# Install Language Servers:
#
#  Rust
#    brew install rust-analyzer
#
#  Python
#    brew install ruff
#    brew install basedpyright
#
#  Lua
#    brew install lua-language-server
#
#  Other
#    brew install taplo
#    brew install prettier
#    brew install yaml-language-server
#    brew install markdown-oxide
#    brew install marksman
#    brew install ltex-ls
#    npm i -g vscode-langservers-extracted

# Rust -------------------------------------------------------------------------

[[language]]
name = "rust"
text-width = 100

[language-server.rust-analyzer.config]
checkOnSave.command = "clippy"

# Python -----------------------------------------------------------------------

[[language]]
name = "python"
auto-format = true
text-width = 88
# https://github.com/helix-editor/helix/issues/1898#issuecomment-1826785304
# The order matters here. Documentation on hover doesn't work the other way around.
language-servers = ["basedpyright", "ruff"]

# ruff ---

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

# Ruff supports hierarchical configuration, such that the "closest" config file
# in the directory hierarchy is used for every individual file, with all paths
# in the config file (e.g., exclude globs, src paths) being resolved relative to
# the directory containing that config file.
#
# https://docs.astral.sh/ruff/configuration/
#
# The following line allows setting the config in Helix.
# [language-server.ruff.config.settings.lint]
# select = []

# basedpyright ---

[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]
except-features = ["format", "code-action"]

[language-server.basedpyright.config]
basedpyright.analysis.typeCheckingMode = "standard"
basedpyright.analysis.diagnosticMode = "workspace"

# formatter ---

[language.formatter]
command = "ruff"
args = ["format", "-"]

# Bash -------------------------------------------------------------------------

[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }

# Lua --------------------------------------------------------------------------

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language-server.lua-language-server.config.Lua]
runtime.version = "LuaJIT"
diagnostics.globals = [
  # Hammerspoon
  "hs",
  "spoon",
]

# Markdown ---------------------------------------------------------------------

[[language]]
name = "markdown"
auto-format = true
text-width = 100

[language.formatter]
command = "prettier"
args = ["--parser", "markdown"]

# CSS --------------------------------------------------------------------------

[[language]]
name = "css"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "css"]

# JSON -------------------------------------------------------------------------

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = "    " }
text-width = 100

[language.formatter]
command = "prettier"
args = ["--parser", "json"]

# TOML -------------------------------------------------------------------------

[[language]]
name = "toml"
auto-format = true

# YAML -------------------------------------------------------------------------

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[language.formatter]
command = "prettier"
args = ["--parser", "yaml"]

# Text -------------------------------------------------------------------------

[[language]]
name = "text"
scope = "source.txt"
file-types = ["txt"]
indent = { tab-width = 2, unit = "  " }
text-width = 100

# INI --------------------------------------------------------------------------

[[language]]
name = "ini"
file-types = [
  "ini",
  # Systemd unit files
  "service",
  "automount",
  "device",
  "mount",
  "path",
  "service",
  "slice",
  "socket",
  "swap",
  "target",
  "timer",
  # Podman quadlets
  "container",
  "volume",
  "kube",
  "network",
  ".editorconfig",
  "properties",
  "cfg",
  "directory",
  # Additions
  "conf",
]
