# https://github.com/helix-editor/helix/blob/master/languages.toml
#
# Install Language Servers:
#   brew install taplo
#   brew install prettier
#   brew install rust-analyzer
#   brew install lua-language-server
#   brew install yaml-language-server
#   brew install ltex-ls
#   brew install pyright
#   pipx install ruff-lsp
#   pipx install python-lsp-server
#   npm i -g vscode-langservers-extracted
#   npm i -g bash-language-server
#   https://github.com/artempyanykh/marksman

# Rust -------------------------------------------------------------------------


[[language]]
name = "rust"
text-width = 100

[language.config]
checkOnSave.command = "clippy"

# Python -----------------------------------------------------------------------

[[language]]
name = "python"
auto-format = true
text-width = 88

[language.formatter]
command = "black"
args = ["-", "--quiet"]

# Lua --------------------------------------------------------------------------

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " }

# [language-server.config]
# Lua.runtime.version = "LuaJIT"
# Lua.diagnostics.globals = [
#   # Hammerspoon
#   "hs",
#   "spoon",
# ]

# Bash -------------------------------------------------------------------------

# https://github.com/helix-editor/helix/issues/6896
[[language]]
name = "bash"
indent = { tab-width = 4, unit = "    " }
file-types = [
  "sh",
  "bash",
  "zsh",
  ".bash_login",
  ".bash_logout",
  ".bash_profile",
  ".bashrc",
  ".profile",
  ".zshenv",
  ".zlogin",
  ".zlogout",
  ".zprofile",
  ".zshrc",
  "APKBUILD",
  "PKGBUILD",
  "eclass",
  "ebuild",
  "bazelrc",
  ".bash_aliases",
  # Additions
  ".aliases",
  ".functions",
]

# Markdown ---------------------------------------------------------------------

[[language]]
name = "markdown"
auto-format = true
indent = { tab-width = 2, unit = "  " }

# Good Markdown LS (Default)
# [language.language-server]
# command = "marksman"

# Good for spell check
# [language.language-server]
# command = "ltex-ls"
# args = []

[language.formatter]
command = "prettier"
args = ["--parser", "markdown"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'_' = '_'
'<' = '>'

# CSS --------------------------------------------------------------------------

[[language]]
name = "css"
auto-format = true

[language.formatter]
command = "prettier"
args = ["--parser", "css"]

# JSON -------------------------------------------------------------------------

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 4, unit = "    " }

# TOML -------------------------------------------------------------------------

[[language]]
name = "toml"
auto-format = true

# YAML -------------------------------------------------------------------------

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

# Ruby -------------------------------------------------------------------------

[[language]]
name = "ruby"
file-types = [
  "rb",
  "rake",
  "rakefile",
  "irb",
  "gemfile",
  "gemspec",
  "Rakefile",
  "Gemfile",
  "rabl",
  "jbuilder",
  "jb",
  "Podfile",
  "podspec",
  # Additions
  "Brewfile",
  "Brewfile-dump",
]

# Text -------------------------------------------------------------------------

[[language]]
name = "text"
scope = "source.txt"
injection-regex = "txt"
file-types = ["txt"]
roots = []
indent = { tab-width = 2, unit = "  " }
