require("config.autopairs")
require("config.bufferline")
require("config.cmp")
require("config.colorscheme")
require("config.comment")
require("config.gitsigns")
require("config.keymaps")
require("config.lsp")
require("config.lualine")
require("config.null-ls")
require("config.nvim-tree")
require("config.options")
require("config.plugins")
require("config.telescope")
require("config.treesitter")
-- require("config.indent")
