inherits = "catppuccin_macchiato"

# https://colors.dopely.top/color-blender/
# https://colors.dopely.top/color-converter/
#
# Default diagnostic colors blended with bg color.
#
# Originals
# bg = "#24273a"
# red = "#ed8796"
# yellow = "#eed49f"
# sky = "#91d7e3"
# teal = "#8bd5ca"

"ui.virtual.ruler" = { bg = "#272a3f" }
"ui.virtual.whitespace" = { fg = "surface0" }
"ui.virtual.inlay-hint" = { fg = "surface1" }

"ui.bufferline" = { fg = "surface2", bg = "mantle" }
"ui.bufferline.active" = { fg = "pink", bg = "base" }

"ui.cursor.normal" = { fg = "base", bg = "green" }
"ui.cursor.insert" = { fg = "base", bg = "pink" }
"ui.cursor.select" = { fg = "base", bg = "green" }

"ui.cursor.primary.normal" = { fg = "base", bg = "pink" }
"ui.cursor.primary.insert" = { fg = "base", bg = "green" }
"ui.cursor.primary.select" = { fg = "base", bg = "red" }

"diagnostic.error" = { bg = "#512F43" }   # red
"diagnostic.warning" = { bg = "#3F3C3E" } # yellow
"diagnostic.hint" = { bg = "#273544" }    # sky
"diagnostic.info" = { bg = "#29324C" }    # teal
