inherits = "catppuccin_macchiato"

"ui.virtual.ruler" = { bg = "#272a3f" }
"ui.virtual.whitespace" = "surface0"

# https://colors.dopely.top/color-blender/
# https://colors.dopely.top/color-converter/
# Default diagnostic colors blended with bg color and saturated by 10%.
"diagnostic.error" = { bg = "#593654" }   # red
"diagnostic.warning" = { bg = "#594554" } # yellow
"diagnostic.info" = { bg = "#2b3555" }    # teal
"diagnostic.hint" = { bg = "#2a3d51" }    # sky
