[lint]
preview = true

select = ["ALL"]

ignore = [
  # Ignore Rule Sets
  "CPY", # flake8-copyright
  "FBT", # flake8-boolean-trap
  "G",   # flake8-logging-format
  "LOG", # flake8-logging (LOG)
  "S",   # flake8-bandit
  "T20", # flake8-print
  "D",   # pydocstyle

  # Ignore Specific Rules
  "ANN401", # any-type
  "D202",   # no-blank-line-after-function
  "E501",   # line-too-long
  "RET504", # unnecessary-assign

  # Ruff warned that ISC001 might cause errors during formatting.
  "ISC001", # single-line-implicit-string-concatenation
]

[lint.isort]
lines-after-imports = 2
