[lint]
preview = true

select = ["ALL"]

ignore = [
  # Ignore Rule Sets
  "S",   # flake8-bandit
  "FBT", # flake8-boolean-trap
  "CPY", # flake8-copyright
  "EM",  # flake8-errmsg
  "FIX", # flake8-fixme
  "G",   # flake8-logging-format
  "LOG", # flake8-logging (LOG)
  "T20", # flake8-print
  "D",   # pydocstyle

  # Ignore Specific Rules
  "ANN002", # missing-type-args
  "ANN003", # missing-type-kwargs
  "ANN401", # any-type
  "D202",   # no-blank-line-after-function
  "E501",   # line-too-long
  "RET504", # unnecessary-assign
  "TD002",  # missing-todo-author
  "TD003",  # missing-todo-link
  "COM812", # missing-trailing-comma
  "TRY003", # raise-vanilla-args

  # This causes issues with 'uv' scripts.
  "ERA001", # commented-out-code

  # Allow non-module scripts.
  "INP001", # implicit-namespace-package

  # Ruff warned that ISC001 might cause errors during formatting.
  "ISC001", # single-line-implicit-string-concatenation
]

[lint.isort]
lines-after-imports = 2
